---
- name: zsh | Install zsh (macOS)
  community.general.homebrew:
    name: zsh
    state: present
  when: ansible_os_family == 'Darwin'

- name: zsh | Install zsh (Arch)
  community.general.pacman:
    name: zsh
    state: present
  become: true
  when: ansible_distribution == 'Archlinux'

- name: zsh | Get zsh path
  ansible.builtin.command: which zsh
  register: zsh_path
  changed_when: false

- name: zsh | Set zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ zsh_path.stdout }}"
  become: true

- name: zsh | Check if Zinit is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/share/zinit/zinit.git"
  register: zinit_stat

- name: zsh | Install Zinit plugin manager
  ansible.builtin.shell:
    cmd: bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
  environment:
    NO_INPUT: "1"
  when: not zinit_stat.stat.exists
  changed_when: true
